name: Use Sync Labels Workflow

on:
  schedule:
   - cron: '0 0 * * 1' # 00:00 on Monday
  workflow_dispatch: # Allows manual triggering
  # You could also add 'schedule', 'push', etc. triggers if needed

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync-labels:
    if: github.repository == 'basher83/Zammad-MCP'
    uses: basher83/.github/.github/workflows/sync-labels.yml@2d27d7bfa6e028b35a0df73cf5c3330ad0a2b7dc # main
   # with:
   #   label_definitions_url: "https://raw.githubusercontent.com/basher83/docs/main/mission-control/github-configs/label-definitions.yml" # optional, can omit for default
